##############
# 19/09/2022 ECID
# Dockerfile to make build of Nginx server of UIC GIN 
FROM nginx:1.17


# Setup temporal
RUN apt-get update && apt-get install nano zip unzip

##############
# Copy Nginx configuration and app to server
COPY config-ng/site.conf /etc/nginx/conf.d/default.conf
COPY SRC/ /var/www/html

##############

# Set timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Madrid /etc/localtime
RUN "date"
EXPOSE 80